version: "3.9"


services:

  #  PostgreSQL Database 
  postgres:
    image: postgres:16-alpine
    container_name: pm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: team12
    volumes:
      
      - /home/azureuser/pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
   
  # Next.js Application 
  next-app:
    image: shrinithi04/project-management-tool:latest
    container_name: pm_nextapp
    restart: unless-stopped
    ports:
      - "3000:3000"          
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NODE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy   
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
